version: '3.8'

services:

  db:
    image: postgres:16
    container_name: sgta_db
    restart: always

    environment:
      POSTGRES_DB: sgta
      POSTGRES_USER: sgta_user
      POSTGRES_PASSWORD: sgta_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sgta_user -d sgta"]
      interval: 5s
      timeout: 5s
      retries: 5


  web:
    image: miirella/pedidos-web:v1
    container_name: pedidos_app
    restart: always

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: