# Generated by Django 6.0.3 on 2026-03-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='status',
            field=models.CharField(choices=[('Aberto', 'ABERTO'), ('Em Preparo', 'EM PREPARO'), ('Finalizado', 'FINALIZADO'), ('Cancelado', 'CANCELADO')], default='ABERTA', max_length=20),
        ),
    ]
